### ISSUE TITLE
Problems with "last update" time

### ISSUE THREAD

**Issue by maksim789456** [hantabaru1014/BetterInventoryBrowser#4]
_Version of mod: latest (v0.5.1)_

Last update time at "detail" layout and sidebar show in UTC+0 time, which is very inconvenient for understanding time.
Example, last update time of the newly saved item and current time:
![image](https://github.com/hantabaru1014/BetterInventoryBrowser/assets/8225008/097501d6-1bf9-4ae0-91b9-1c82cf88e680)

But after restart NeosVr, last update time converts to local, and it's making problems with sorting by update time.
Example, folder contains item saved at past open of NeosVr (at item update time show in local time). I save in this folder new item and update time shows as UTC time:
![image](https://github.com/hantabaru1014/BetterInventoryBrowser/assets/8225008/1a90b246-f3a0-4747-b273-f41cd0824116)

**Comment by hantabaru1014** [comment]
Thank you for your report, it fixed in v0.5.2.
