### ISSUE TITLE
Disfunctional legacy inventory since v0.5.0

### ISSUE THREAD

**Issue by CyanTabby** [hantabaru1014/BetterInventoryBrowser#5]
The legacy inventory seems to have broken UI elements after release v0.5.0.
Items can still be spawned, but when they are selected it doesn't show the name or allow other actions to be performed (share, delete, favorite, equip, etc.)
## Item selected in v0.4.1:
![Screenshot 2023-05-16 154540](https://github.com/hantabaru1014/BetterInventoryBrowser/assets/69196138/b1f5b585-8041-41a8-8fb7-515eb7955d08)
## Item selected in v0.5.0 & v0.5.1:
![Screenshot 2023-05-16 154933](https://github.com/hantabaru1014/BetterInventoryBrowser/assets/69196138/f98a2cc5-5288-47d9-9ed7-bbfacb73e796)

**Comment by hantabaru1014** [comment]
Thank you for your report, it fixed in v0.5.2.
