### ISSUE TITLE
Broken in new settings UI prerelease (Beta 2024.4.3.1385)

### ISSUE THREAD

**Issue by Nytra** [hantabaru1014/BetterInventoryBrowser#8]
Inventory does not work at all

[DESKTOP-H976HO2 - 2024.4.3.1385 - 2024-04-04 03_12_17.log](https://github.com/hantabaru1014/BetterInventoryBrowser/files/14860490/DESKTOP-H976HO2.-.2024.4.3.1385.-.2024-04-04.03_12_17.log)

**Comment by hantabaru1014** [comment]
thanks for your report.  
fixed: https://github.com/hantabaru1014/BetterInventoryBrowser/releases/tag/v0.6.2
